### ISSUE TITLE
Failing on no bin setting set?

### ISSUE THREAD

**Issue by nyonson** [yasudanaoya/gotests.nvim#1]
Seeing this recently:

```
Error executing Lua callback: Vim:E1174: String required for argument 1
stack traceback:
        [C]: in function 'executable'
        ...te/pack/paqs/start/gotests-nvim/lua/gotests/autoload.lua:19: in function 'tests'
        ...e/nvim/site/pack/paqs/start/gotests-nvim/lua/gotests.lua:27: in function <...e/nvim/site/pack/paqs/start/gotests-nvim/lua/gotests.lua:26>
```

I don't have any settings explicitly set, and taking a look at the code, maybe that is causing an issue?

**Comment by zach-wahrer** [comment]
I'm having this same issue as well recently.

**Comment by yanskun** [comment]
@nyonson @zach-wahrer 
Sorry I noticed too late.

Thank you.

It's been a while since I did Go development, and I'm the same.
Investigate. please wait a little bit.

**Comment by yanskun** [comment]
@nyonson @zach-wahrer
fixed

It was caused by not being able to call the `gotests` binary well.

I found some improvements and will continue to fix them.😊

**Comment by yanskun** [comment]
`vim.g.gotests_bin` was nil for some reason.
It was probably the case with everyone.

And it was `exists(nil) == true`...
I haven't studied enough 😭

**Comment by zach-wahrer** [comment]
Thanks for fixing this!
